name: Check Composable Files for Hardcoded Values

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-hardcoded-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          java-package: jdk
          architecture: x64
          check-latest: false

      - name: Find hardcoded values in composable files
        id: find-hardcoded-values
        run: |
          set -e
          FILES=$(find app/src/main/java -name '*.kt')
          WARNINGS=""
          for file in $FILES; do
            LINES=$(grep -nE '("[^"]*"|[0-9]+\.dp)' $file | grep -v 'const val') || true
            if [ ! -z "$LINES" ]; then
              WARNINGS="$WARNINGS\n$file:\n$LINES"
            fi
          done
          if [ -z "$WARNINGS" ]; then
            echo "No hardcoded values found."
          else
            echo "WARNINGS<<EOF" >> $GITHUB_ENV
            echo -e "$WARNINGS" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "::warning::Hardcoded values found:\n$WARNINGS"
          fi
        shell: /usr/bin/bash -e {0}
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.14-7/x64

      - name: Post warnings as comments
        if: env.WARNINGS != ''
        uses: actions/github-script@v5
        with:
          script: |
            const warnings = process.env.WARNINGS.split('\n');
            let commentBody = '### Hardcoded Values Warning\n';
            warnings.forEach(line => {
              if (line.trim() !== '') {
                commentBody += `${line}\n`;
              }
            });
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody
            });
