name: PR Linting

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-hardcoded-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          java-package: jdk
          architecture: x64
          check-latest: false

      - name: Get list of changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            app/src/main/java/**/*.kt

      - name: Find hardcoded values in changed lines
        id: find-hardcoded-values
        run: |
          set -e
          DETAILS=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            FILE_NAME=$(basename $file)
            DIFF_LINES=$(git diff HEAD^ --unified=0 $file | grep -E '^\+[^+]' | grep -nE '"[^"]*"|[0-9]+\.dp' | grep -v 'const val' | grep -v '@SerializedName') || true
            if [ ! -z "$DIFF_LINES" ]; then
              DETAILS+="$file|$DIFF_LINES|Hardcoded value found in $file\n"
            fi
          done
          echo "$DETAILS" > details.txt
        shell: /usr/bin/bash -e {0}

      - name: Post warnings as comments
        if: steps.find-hardcoded-values.outputs.DETAILS != ''
        uses: actions/github-script@v5
        run: |
          node <<EOF
          const fs = require('fs');
          const github = require('@actions/github');
          const context = github.context;

          const details = fs.readFileSync('details.txt', 'utf8');
          const lines = details.split('\\n');

          lines.forEach(line => {
            if (line.trim() !== '') {
              const [file, diff_lines, message] = line.split('|');
              github.rest.pulls.createReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                body: message,
                commit_id: context.payload.pull_request.head.sha,
                path: file,
                line: parseInt(diff_lines.split(':')[0])
              });
            }
          });
          EOF
        shell: node