name: ViewModel Unit Tests

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  viewmodel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Environment
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ADMOB_APP_KEY=${{ secrets.ADMOB_APP_KEY }}" >> local.properties
          echo "PLACES_KEY=${{ secrets.PLACES_KEY }}" >> local.properties
          echo "OPENWEATHER_KEY=${{ secrets.OPENWEATHER_KEY }}" >> local.properties

      - name: Fetch modified ViewModel files
        id: fetch-modified-viewmodel-files
        run: |
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD | grep 'ViewModel\.kt$')
          echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV

      - name: Check for Corresponding Test Files
        id: check-test-files
        uses: actions/github-script@v5
        with:
          script: |
            const modifiedFiles = process.env.MODIFIED_FILES.split('\n').filter(Boolean);
            let missingTestFiles = '';
            let testFiles = '';

            for (const file of modifiedFiles) {
              const testFile1 = file.replace('ViewModel.kt', 'ViewModelTest.kt');
              const testFile2 = file.replace('ViewModel.kt', 'ViewModelTests.kt');
              const testFilePath1 = `app/src/test/java/${testFile1}`;
              const testFilePath2 = `app/src/test/java/${testFile2}`;

              if (!fs.existsSync(testFilePath1) && !fs.existsSync(testFilePath2)) {
                missingTestFiles += `\n${testFile1}\n${testFile2}`;
              } else {
                testFiles += ` ${testFilePath1} ${testFilePath2}`;
              }
            }

            core.exportVariable('TEST_FILES', testFiles.trim());

            if (missingTestFiles.trim()) {
              core.exportVariable('MISSING_TEST_FILES', 'true');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `Error: Missing test files for modified ViewModel files:${missingTestFiles}`
              });
            } else {
              core.exportVariable('MISSING_TEST_FILES', 'false');
            }

      - name: Cache Gradle build cache
        if: env.TEST_FILES != ''
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        if: env.TEST_FILES != ''
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'

      - name: Set up Android SDK
        if: env.TEST_FILES != ''
        uses: android-actions/setup-android@v3

      - name: Generate Coverage Report
        if: env.TEST_FILES != ''
        run: ./gradlew createDebugUnitTestCoverageReport
        continue-on-error: true

      - name: Post Coverage Report
        if: env.TEST_FILES != ''
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const testFiles = process.env.TEST_FILES.split(' ').filter(Boolean);
            let coverageDetails = '### Total Test Coverage:\n\n| Class | Line Coverage | Method Coverage |\n|-------|---------------|-----------------|\n';
            let missingTests = '';

            for (const file of testFiles) {
              const className = path.basename(file).replace('Test.kt', '').replace('Tests.kt', '').replace('.kt', '');
              const coverageFilePath = path.join('app/build/reports/coverage/test/debug', `${className}.html`);

              if (fs.existsSync(coverageFilePath)) {
                const report = fs.readFileSync(coverageFilePath, 'utf8');
                const lineCoverage = report.match(/<td class="ctr2">(\d+)%<\/td>/)[1];
                const methodCoverage = report.match(/<td class="ctr2">(\d+)%<\/td>/)[1];

                coverageDetails += `| ${className} | ${lineCoverage}% | ${methodCoverage}% |\n`;
              } else {
                missingTests += `\n${className}`;
              }
            }

            if (coverageDetails.trim() !== '### Total Test Coverage:\n\n| Class | Line Coverage | Method Coverage |\n|-------|---------------|-----------------|\n') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: coverageDetails
              });
            }

            if (missingTests.trim()) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `**Error:** Missing test coverage for the following classes:${missingTests}`
              });
            }